# Site Configs
name: Ionic Framework
description: The official Ionic Framework blog
url: http://ionicframework.com/blog
markdown: redcarpet
pygments: true
permalink: /blog/:title
paginate: 5

# Default news if the page didnt enter news
news: First time using Ionic? We recommend reading our <a href="/docs/guide/">Guide</a>, which covers all the basics of setting up an Ionic mobile app.

# Latest Version Config
latest_download: https://github.com/driftyco/ionic/releases/tag/v0.9.16-alpha
latest_version: 0.9.16 "Alpha Hippo"
latest_release_date: December 11th, 2013

# Which version of AngularJS the latest build includes
included_angular_version: 1.2.4

# Docs Location Config
docs_0_9_0: /docs
