name: Ionic Framework
description: The official Ionic Framework blog
url: http://ionicframework.com/blog
markdown: redcarpet
pygments: true
permalink: /blog/:title
paginate: 5
latest_api_version: "0.9.0"