# Site Configs
name: Ionic Framework
description: The official Ionic Framework blog
url: http://ionicframework.com/blog
markdown: redcarpet
pygments: true
permalink: /blog/:title
paginate: 5

# Default news if the page didnt enter news
news: First time using Ionic? We recommend reading our <a href="/docs/guide/">Guide</a>, which covers all the basics of setting up an Ionic mobile app.

# Latest Version Config
latest_download: https://github.com/driftyco/ionic/archive/v0.9.21-alpha.zip
latest_version: 0.9.21 "Alpha Maine Coon"
latest_release_date: January 24th, 2014

# Which version of AngularJS the latest build includes
included_angular_version: 1.2.8

# Which active Cordova version we recommend
recommended_cordova_version: 3.3.1

# Docs Location Config
docs_0_9_0: /docs

# the primary plunkr to fork
code_sample_base_url: http://plnkr.co/edit/vD0O9M?p=preview
